version: "3.5"

volumes:
  mongo-data:

    null
x-common-environment:
  &common-environment
  image: node:16
  working_dir: /app
  volumes:
    - ./:/app
  restart: on-failure
  env_file:
    - ./.env
  depends_on:
    - mongodb
  links:
    - mongodb

services:
  amm-users:
    <<: *common-environment
    command: "npm run job:get-amm-users"

  mongodb:
    image: mongo:5.0
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - target: 27017
        published: 27017
  # redis:
  #   image: redis:alpine
