version: "3.5"

volumes:
  mongo-data:

    null
x-base-service:
  &base-service
  image: node:16
  working_dir: /app
  volumes:
    - ./src:/app
  restart: on-failure
  env_file:
    - .env
  depends_on:
    - mongodb

services:
  # amm-users:
  #   <<: *base-service
  #   command: "npm run job:get-amm-users"

  mongodb:
    image: mongo:4.4
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - target: 27017
        published: 27017
  # redis:
  #   image: redis:alpine
